---
- name: Enable filebeat modules
  shell:
    cmd: filebeat modules enable {{item}}
  with_items: "{{ filebeat_modules }}"

- name: Enable custom configs for enabled modules
  template:
    src: module.yml.j2
    dest:  "{{ filebeat_config_path | dirname }}/{{ item.module }}.yml"
    mode: 0644
    owner: root
    group: root
  when: item in filebeat_modules
  with_items: "{{ filebeat_module_configs }}"
