---
- name: Enable filebeat modules
  command: filebeat modules enable {{ item }}
  with_items: "{{ filebeat_modules }}"
  when: filebeat_modules | length > 0

- name: Enable custom configs for enabled modules
  template:
    src: module.yml.j2
    dest: "{{ filebeat_config_path | dirname }}/{{ item.module }}.yml"
    mode: 0644
    owner: root
    group: root
  with_items: "{{ filebeat_module_configs }}"
