---
- name: Enable filebeat modules
  command: filebeat modules enable {{ item }}
  with_items: "{{ filebeat_modules }}"
  when: filebeat_modules | length > 0

- name: Enable custom configs for enabled modules
  template:
    src: "{{ item }}"
    dest: "{{ filebeat_config_path | dirname }}"
    mode: 0644
    owner: root
    group: root
    with_fileglob: "{{ filebeat_module_configs }}"
