---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Filebeat.
  package: name=filebeat state=present

- include: config.yml
  when: filebeat_create_config | bool
  tags: [copy_filebeat_config]

- include: enable_modules.yml
  when: filebeat_enable_modules | bool
  tags: [enable_filebeat_module]

- name: Ensure Filebeat is started and enabled at boot.
  service:
    name: filebeat
    state: started
    enabled: true
